[build]
  # 指定构建命令
  command = "npm run build" 

  # 指定输出目录，Vue 默认是 dist
  publish = "dist123" 

  # 环境变量（可选）
  [build.environment]
    NODE_VERSION = "18"

[[redirects]]
  # 配置 SPA 重定向，防止刷新页面时出现 404
  from = "/*"
  to = "/index.html"
  status = 200
